### ISSUE TITLE
I am facing a issue

### ISSUE THREAD

**Issue by vipuluthaiah** [sainiteshb/News-App-Flutter#9]
![image](https://user-images.githubusercontent.com/45168922/96551352-c2c2ab00-12cf-11eb-8827-3ff6a9e8fd7e.png)
![image](https://user-images.githubusercontent.com/45168922/96551361-c8b88c00-12cf-11eb-8d74-25ae8450fb46.png)
why is it showing 
In Review?
should i b aware of something?

**Comment by sainiteshb** [comment]
That it not an issue ! Are you participating for the first time? Thats the process that happens till your PR gets accepted for hactoberfest , you need not do anything ,its review period . Close the issue.
